sbatch ./sbatch_hpc_hdbscan.sh train.0.json
sbatch ./sbatch_hpc_hdbscan.sh train.1.json
sbatch ./sbatch_hpc_hdbscan.sh train.2.json
sbatch ./sbatch_hpc_hdbscan.sh train.3.json
sbatch ./sbatch_hpc_hdbscan.sh train.4.json
sbatch ./sbatch_hpc_hdbscan.sh train.5.json
sbatch ./sbatch_hpc_hdbscan.sh train.6.json
sbatch ./sbatch_hpc_hdbscan.sh train.7.json
sbatch ./sbatch_hpc_hdbscan.sh train.8.json
sbatch ./sbatch_hpc_hdbscan.sh train.9.json
sbatch ./sbatch_hpc_hdbscan.sh train.10.json
sbatch ./sbatch_hpc_hdbscan.sh train.11.json
sbatch ./sbatch_hpc_hdbscan.sh train.12.json
sbatch ./sbatch_hpc_hdbscan.sh train.13.json
sbatch ./sbatch_hpc_hdbscan.sh validation.0.json
sbatch ./sbatch_hpc_hdbscan.sh validation.1.json
sbatch ./sbatch_hpc_hdbscan.sh test.0.json
sbatch ./sbatch_hpc_hdbscan.sh test.1.json
